CREATE TYPE "Role" AS ENUM ('ADMIN', 'EMPLOYEE');
CREATE TYPE "AttendanceStatus" AS ENUM ('PRESENT', 'ABSENT', 'HALFDAY', 'LEAVE');
CREATE TYPE "LeaveType" AS ENUM ('PAID', 'SICK', 'UNPAID');
CREATE TYPE "LeaveStatus" AS ENUM ('PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "NotificationType" AS ENUM ('LEAVEUPDATE', 'ATTENDANCEALERT', 'GENERAL');

CREATE TABLE "User" ("id" TEXT NOT NULL, "employeeId" TEXT NOT NULL, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "role" "Role" NOT NULL DEFAULT 'EMPLOYEE', "isEmailVerified" BOOLEAN NOT NULL DEFAULT false, "verificationToken" TEXT, "verificationExpiresAt" TIMESTAMP(3), "refreshToken" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "EmployeeProfile" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "fullName" TEXT NOT NULL, "phone" TEXT, "address" TEXT, "profilePictureUrl" TEXT, "department" TEXT, "designation" TEXT, "dateOfJoining" TIMESTAMP(3), "managerId" TEXT, CONSTRAINT "EmployeeProfile_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Document" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "docType" TEXT NOT NULL, "fileUrl" TEXT NOT NULL, "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Document_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Attendance" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "date" DATE NOT NULL, "checkIn" TIMESTAMP(3), "checkOut" TIMESTAMP(3), "status" "AttendanceStatus" NOT NULL DEFAULT 'PRESENT', "note" TEXT, CONSTRAINT "Attendance_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LeaveRequest" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "leaveType" "LeaveType" NOT NULL, "startDate" DATE NOT NULL, "endDate" DATE NOT NULL, "remarks" TEXT, "status" "LeaveStatus" NOT NULL DEFAULT 'PENDING', "reviewerId" TEXT, "reviewerComment" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "LeaveRequest_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SalaryStructure" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "baseSalary" DECIMAL(12,2) NOT NULL, "allowances" DECIMAL(12,2) NOT NULL, "deductions" DECIMAL(12,2) NOT NULL, "effectiveFrom" DATE NOT NULL, "updatedBy" TEXT NOT NULL, CONSTRAINT "SalaryStructure_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Notification" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "message" TEXT NOT NULL, "type" "NotificationType" NOT NULL, "isRead" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Notification_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "User_employeeId_key" ON "User"("employeeId"); CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "User_verificationToken_key" ON "User"("verificationToken"); CREATE UNIQUE INDEX "EmployeeProfile_userId_key" ON "EmployeeProfile"("userId"); CREATE INDEX "Document_userId_idx" ON "Document"("userId"); CREATE UNIQUE INDEX "Attendance_userId_date_key" ON "Attendance"("userId", "date"); CREATE INDEX "Attendance_userId_date_idx" ON "Attendance"("userId", "date"); CREATE INDEX "LeaveRequest_userId_startDate_endDate_idx" ON "LeaveRequest"("userId", "startDate", "endDate"); CREATE INDEX "LeaveRequest_status_idx" ON "LeaveRequest"("status"); CREATE INDEX "SalaryStructure_userId_effectiveFrom_idx" ON "SalaryStructure"("userId", "effectiveFrom"); CREATE INDEX "Notification_userId_isRead_idx" ON "Notification"("userId", "isRead");

ALTER TABLE "EmployeeProfile" ADD CONSTRAINT "EmployeeProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "EmployeeProfile" ADD CONSTRAINT "EmployeeProfile_managerId_fkey" FOREIGN KEY ("managerId") REFERENCES "User"("id") ON DELETE SET NULL; ALTER TABLE "Document" ADD CONSTRAINT "Document_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "Attendance" ADD CONSTRAINT "Attendance_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "LeaveRequest" ADD CONSTRAINT "LeaveRequest_reviewerId_fkey" FOREIGN KEY ("reviewerId") REFERENCES "User"("id") ON DELETE SET NULL; ALTER TABLE "SalaryStructure" ADD CONSTRAINT "SalaryStructure_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE; ALTER TABLE "SalaryStructure" ADD CONSTRAINT "SalaryStructure_updatedBy_fkey" FOREIGN KEY ("updatedBy") REFERENCES "User"("id"); ALTER TABLE "Notification" ADD CONSTRAINT "Notification_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE;
